### ISSUE TITLE
Seção 11: Tópicos especiais em Java: Data-hora

### ISSUE THREAD

**Issue by salvedojuliao** [salvedojuliao/course-java-POO#16]
## 📌 Introdução a data-hora e duração

**- Data-[hora] local:**
 - ano-mês-dia-hora sem fuso horário
 - [hora] opcional;
**_Obs:_** Quando a gente registra uma data local, a hora é opcional!

**- Data-hora global:**
 - ano-mês-dia-hora com fuso horário;
**_Obs:_** A data hora local é armazenda sem fuso-horario e a data hora global é registrada com fuso-horário.

![2023-04-22_09h38_06](https://user-images.githubusercontent.com/44206400/233785165-c6676097-7f78-41b0-b65c-4ccfa4f4c579.png)

O programa precisa ler a data de que eu recebo por meio de uma API no banco de dados e conseguir diferenciar de acordo com os fuso-horários de países diferentes:

![2023-04-22_09h40_42](https://user-images.githubusercontent.com/44206400/233785271-78d041fe-c7eb-42be-b441-4dc051234b76.png)

Contúdo, em alguns casos a hora local é mais indicada:

**- Data-[hora] local:**
Quando o momento exato não interessa a pessoas de outro fuso horário.
Uso comum: sistemas de região única, excel:

**- Data-[hora] global:**
Quando o momento exato interessa a pessoas de outro fuso-horário.
Uso comum: sustemas multi-região, web, live de futebol, jogo;

![2023-04-22_09h44_12](https://user-images.githubusercontent.com/44206400/233785422-1fcc7699-b3ec-4060-b64c-a11081de29e9.png)

**Comment by salvedojuliao** [comment]
## 📌 Entendendo timezone (fuso horário)

**- GMT - Greenwich Mean Time**
 -  Horário de Londres;
 - Horário do Padrão UTC - Coordinated Universal Time;
 - Também chamado de "Z" time, ou Zulu time

**- Outro fuso horários são relativos ao GMT/UTC**
 - São Paulo: GMT-3;
 - Manaus: GMT-4;
 - Portugal: GMT+1

**Muitas linguagens/tecnologias usam nomes para as timezones:**
- "US/Pacific"
- "America/Sao_Paulo"
- etc.

**Comment by salvedojuliao** [comment]
## 📌Padrão ISO 8601

**- Data-[hora] local:**

2022-07-21 (Só data)
2022-07-21T14:52 (Data + hora e minutos)
2022-07-21T14:52:09 (Data + hora e minutos + segundos)
2022-07-21T14:52:09.4073 (Data + hora e minutos + segundos + fração de segundos)

**- Data-[hora] global:**
2022-07-23T14:52:09**Z** (Data + horas, minutos e segundos no tempo zulu, ou seja, Greenwitch time) 
2022-07-23T14:52:09.254935**Z** (Data + horas, minutos + segundos e fração de segundos no tempo zulu, ou seja, Greenwitch time) 
2022-07-23T14:52:09-03:00 (Data + horas, minutos e segundos com 3 horas de atrasado em relação ao zulu time)

**Comment by salvedojuliao** [comment]
## 📌 Operações importantes com data-hora

### 🛠️ Instaciação:

**(agora) -> Data-hora**
Instanciar um objeto como a hora do horário da instanciação: comum em pedidos

**Texto ISO 8601 -> Data-hora**
Eu acesso uma API com resultado em uma requisção WEB (que só trafega texto), ou seja, virá uma data em forma de texto.
Em seguida eu converto esse texto em um objeto data-hora da minha linguagem;

**Texto formato customizado -> Data-hora**
Um texto em outro formato (diferente do ISO);

**dia, mês, ano [horário] -> Data-hora local**
Eu instancio uma Data-hora seguindo informações soltas, ou seja, eu defino dados distindos e instancio uma data.


### 🛠️ Formatação:

Data-hora -> Texto ISO 8601
Eu preciso saber formtar uma Data-hora para textos!

**Data-hora -> Texto formato customizado**

![2023-04-22_10h18_08](https://user-images.githubusercontent.com/44206400/233787441-eb29eacb-78bf-4045-bdd3-9b268e169ee7.png)

**Obter dados de uma data-hora local**
Eu preciso saber extrair dados de uma data-hora

**Converter data-hora global para local**
Data-hora global, timezone (sistema local) -> Data-hora local

**Cálculos com data-hora**
Data-hora +/- tempo -> Data-hora
Data-hora 1, Data-hora 2 -> duração
(Calcular a duração de tempo, adicionar ou remover mais horas)

![2023-04-22_10h21_17](https://user-images.githubusercontent.com/44206400/233787581-475c7a74-8bb6-404d-b59e-bfebaef4f21e.png)

**Comment by salvedojuliao** [comment]
## 📌 Instanciando data-hora em Java
![2023-04-22_10h22_45](https://user-images.githubusercontent.com/44206400/233787647-098baa9d-7e32-468f-83ee-29640115255d.png)

**Comment by salvedojuliao** [comment]
**PDF:**
[trabalhando-com-data-hora.pdf](https://github.com/salvedojuliao/course-java-POO/files/11301675/trabalhando-com-data-hora.pdf)

**Comment by salvedojuliao** [comment]
**PDF:**
[trabalhando-com-data-hora.pdf](https://github.com/salvedojuliao/course-java-POO/files/11301675/trabalhando-com-data-hora.pdf)

**Comment by salvedojuliao** [comment]
## Somando uma unidade de tempo

**Comment by JayCesar** [comment]
## Revisão
### Conceitos Importantes
- Quando eu registro uma hora local, a hora é opcional!
- A data hora local é registrada sem fuso-horário 
- Duração: Tempo decorrido entre duas dta-horas
- O fuso-horário precisa calcular considerando o fuso-horário caso minha aplicação interessa pessoas de outro fuso-horário.
**- Data-hora local vs Data-hora Global (esse o fuso interessa)**

____

### Timezone (fuso horário)
**GMT - Greenwitch Mean Time**
- Horário de Londres
- Horário do Padrão UTC - Coordinated Universal Time
- Também chamado de "Z" time ou Zulu time

**Outros fuso horários são relativos ao GMT/UTC**
- São Paulo: GMT-3
- Manaus: GMT-4
- Portugal: Portugal: GMT+1 
Isso então (o número do lado do GMT) o indicativo de quantas horas a mais ou menos em relação ao GMT

____

### Padrão ISO 8601
- O "T" indica o tempo (time);

- Data-[hora] local:

2022-07-21 (Só data)
2022-07-21T14:52 (Data + hora e minutos)
2022-07-21T14:52:09 (Data + hora e minutos + segundos)
2022-07-21T14:52:09.4073 (Data + hora e minutos + segundos + fração de segundos)

- Data-[hora] global:
- O "Z" indica ozulu time;

2022-07-23T14:52:09Z (Data + horas, minutos e segundos no tempo zulu, ou seja, Greenwitch time)
2022-07-23T14:52:09.254935Z (Data + horas, minutos + segundos e fração de segundos no tempo zulu, ou seja, Greenwitch time)
2022-07-23T14:52:09-03:00 (Data + horas, minutos e segundos com 3 horas de atraso em relação ao zulu time)
Esse tracinho é (menos '-' 3);

____

## Operações importantes com data-hora

**Instanciação**
1 - Eu preciso saber instanciar um ojeto do tipo de Data-Hora
2 - Eu preciso saber instanciar uma DataHora a partir do texto (requisição web). Eu preciso converter o objeto!
3 - Texto fortmato customizado -> Preciso manipular o texto para converter em uma Data-Hora
4 - dia, mês, ano [horário] -> preciso converter para Data-Hora Local

**Formatação**
- Data-hora a partir do ISO de textos;

Obs: Converter data-hora global par alocal eu preciso do timezone!

Eu preciso também fazer cálculos com daa-hora! Eu preciso também Saber fazer a duração entre datas

____

## Instanciando data-hora em Java

**Para representar data hora local** 
- LocalDate
- LocalDateTime (quando tenho que armazenar horário

**Para representar data hora Global**
- Instant (vem com fusu horário)

**Duração**
É o tipo duration

**Outros** 
ZoneId
ChornoUnit
