### ISSUE TITLE
Seção 5: estrutura condicional

### ISSUE THREAD

**Issue by salvedojuliao** [salvedojuliao/course-java-POO#5]
## 📌 Expressões comparativas
São aquelas expressões que comparam uma coisa com outra e resultam num valor vedade (verdadeiro ou falso)

![2023-04-04_21h37_08](https://user-images.githubusercontent.com/44206400/229952327-e25f5dc6-c8c0-4ea7-8c40-b1c56b7be953.png)

## 📌 Expressões Lógicas
Também resultado num valor verdade (verdadeiro ou falso)
![2023-04-04_21h39_28](https://user-images.githubusercontent.com/44206400/229952558-d1c5a611-65f9-4a4e-a214-81c1bc83f0ef.png)

## 📌 Estrutura Condicional
É uma estrutura de controle que permite definir que um certo **bloco de comandos** somente será executado dependendo de um **condição**. Ou seja, agora eu tenho um controle para direcionar o fluxo do programa dependendo se a condição for verdadeira ou falsa. 

**Estrutura Simples**
![2023-04-04_21h52_22](https://user-images.githubusercontent.com/44206400/229953955-026482ed-b495-44cf-a88d-ce3069f0df61.png)

**Estrutura Composta**
![2023-04-04_21h56_46](https://user-images.githubusercontent.com/44206400/229954488-02f5a558-6275-4adc-8d5a-f1e91b906a71.png)

**E se eu tiver mais de duas possibilidades?**
Eu posso fazer um encadeamento de estruturas condicionais!
![2023-04-04_22h04_43](https://user-images.githubusercontent.com/44206400/229955245-13c0fac2-2e89-4d0d-8519-da6f5aca6ac8.png)

______

## 📌Operadores de atribuição cumulativa

![2023-04-06_16h49_40](https://user-images.githubusercontent.com/44206400/230480111-3427f55a-8200-40d2-baf3-4dba3ba5b5f9.png)

## 📌Estrutura switch-case
Quando se tem várias opções de fluxo a serem tratadas com base no valor de uma variável, ao invés de várias estruturas if-else encadeadas, alguns preferem utilizar a estrutura switch-case.
![2023-04-06_17h53_23](https://user-images.githubusercontent.com/44206400/230491748-672ae5ed-522e-4c25-a24e-709c03cfe703.png)

## 📌Expressão condicional Ternária
Estrutura opcional ao if-else quando se deseja decidir um VALOR com base em uma condição;

**Sintaxe:**
( condição ) ? valor_se_verdadeiro : valor_se_falso;
![2023-04-06_17h55_59](https://user-images.githubusercontent.com/44206400/230492219-0fc9857b-0955-4ff1-bf16-9ea60c27791d.png)

## 📌 Escopo e inicialização
- Escopo de uma variável é a região do programa onde a variável é válida, ou seja, onde ela podeser referenciada;
- Uma variável não pode ser usada se não for iniciada;

**_Obs:_** Todas as variáveis que eu declarara dentro de uma esturutra condicional irão exsitir somente dentro dessa estrutura. Ou seja, deixarão de existir assim que a estrutura acabar;

![2023-04-06_18h01_49](https://user-images.githubusercontent.com/44206400/230493227-98d6cae5-d2a8-45ea-9aaa-1c96302e3712.png)

______ 

[05-estrutura-condicional (1).pdf](https://github.com/salvedojuliao/course-java-POO/files/11174433/05-estrutura-condicional.1.pdf)

**Comment by anabiax** [comment]
teste 1

**Comment by salvedojuliao** [comment]
Ótimo
